### ISSUE TITLE
Mate Volume Control Applet - Arrow Keys Don't Work

### ISSUE THREAD

**Issue by karakartala** [mate-desktop/mate-media#94]
#### Expected behaviour

I have updated my LinuxMint from 18.1 to 18.2. Formerly, When I clicked volume control applet, I could control the volume level through up/down keys.
#### Actual behaviour

But now, arrow keys don't control the volume level. Despite clicking volume applet, arrow keys work in where the mouse is.
#### MATE general version

MATE 1.18.0
#### Linux Distribution

Linux Mint 18.2

**Comment by monsta** [comment]
Confirmed, appeared with migration to GTK+3.

**Comment by lukefromdc** [comment]
Confirmed here as well, applet does not seem to capture the keyboard, which continues to control the last window to have focus. Volume (media) keys still work as they do not require focus. I didn't catch this in the initial GTK3 migration because I never knew the arrow keys could be used with the applet.
